import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { promises as fs } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import { IndexGenerator } from '../index-generator.js';

const ALL_PHASES = {
  requirements: '# Requirements\n',
  design: '# Design\n',
  tasks: '- [x] 1. Done task\n- [ ] 2. Pending task\n',
};

describe('IndexGenerator', () => {
  let tempDir: string;
  let generator: IndexGenerator;

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(join(tmpdir(), 'index-gen-test-'));
    await fs.mkdir(join(tempDir, '.spec-workflow', 'specs'), { recursive: true });
    generator = new IndexGenerator(tempDir);
  });

  afterEach(async () => {
    await fs.rm(tempDir, { recursive: true, force: true });
  });

  async function createSpec(name: string, files: Partial<typeof ALL_PHASES> = ALL_PHASES) {
    const dir = join(tempDir, '.spec-workflow', 'specs', name);
    await fs.mkdir(dir, { recursive: true });
    if (files.requirements !== undefined) await fs.writeFile(join(dir, 'requirements.md'), files.requirements);
    if (files.design !== undefined) await fs.writeFile(join(dir, 'design.md'), files.design);
    if (files.tasks !== undefined) await fs.writeFile(join(dir, 'tasks.md'), files.tasks);
  }

  async function writeDecomposition(content: string) {
    const dir = join(tempDir, '.spec-workflow', 'spec-decomposition');
    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(join(dir, 'decomposition.md'), content);
  }

  async function readIndex(): Promise<string> {
    return fs.readFile(join(tempDir, '.spec-workflow', 'spec-decomposition', 'INDEX.md'), 'utf-8');
  }

  it('marks the file as auto-generated', async () => {
    await generator.generate();
    const index = await readIndex();
    expect(index).toContain('AUTO-GENERATED by spec-workflow-mcp');
    expect(index).toContain('# Spec Roadmap');
  });

  it('orders active specs by their first mention in decomposition.md', async () => {
    await createSpec('alpha');
    await createSpec('bravo');
    await createSpec('charlie');
    await writeDecomposition('# Plan\n\n1. charlie\n2. alpha\n3. bravo\n');

    const result = await generator.generate();
    expect(result.active).toBe(3);

    const index = await readIndex();
    const order = ['charlie', 'alpha', 'bravo'].map(n => index.indexOf(`| ${n} |`));
    expect(order[0]).toBeLessThan(order[1]);
    expect(order[1]).toBeLessThan(order[2]);
    expect(index).toContain('| 1 | charlie |');
    expect(index).toContain('| 3 | bravo |');
  });

  it('derives the status label per phase', async () => {
    await createSpec('needs-reqs', {}); // empty spec dir → requirements not yet started
    await createSpec('done', {
      requirements: '# R\n',
      design: '# D\n',
      tasks: '- [x] 1. a\n- [x] 2. b\n',
    });
    await writeDecomposition('needs-reqs\ndone\n');

    await generator.generate();
    const content = await readIndex();
    expect(content).toMatch(/\| needs-reqs \| Requirements \| — \|/);
    expect(content).toMatch(/\| done \| Complete \| 2\/2 \|/);
  });

  it('renders a Deferred section and excludes deferred specs from Active', async () => {
    await createSpec('alpha');
    await createSpec('bravo');
    await writeDecomposition('alpha\nbravo\n');

    await generator.defer('bravo', 'Postponed until post-launch');
    const result = await generator.generate();

    expect(result.active).toBe(1);
    expect(result.deferred).toBe(1);

    const index = await readIndex();
    expect(index).toContain('## Deferred');
    expect(index).toContain('| bravo | Implementing | Postponed until post-launch |');
    // bravo must not appear in the Active table
    const activeSection = index.slice(index.indexOf('## Active'), index.indexOf('## Deferred'));
    expect(activeSection).not.toContain('| bravo |');
  });

  it('undefer returns a spec to the active roadmap', async () => {
    await createSpec('alpha');
    await writeDecomposition('alpha\n');

    await generator.defer('alpha', 'later');
    await generator.undefer('alpha');
    const result = await generator.generate();

    expect(result.deferred).toBe(0);
    expect(result.active).toBe(1);
    const index = await readIndex();
    expect(index).not.toContain('## Deferred');
  });

  it('lists specs missing from decomposition.md under Other specs', async () => {
    await createSpec('alpha');
    await createSpec('orphan');
    await writeDecomposition('alpha\n');

    const result = await generator.generate();
    expect(result.active).toBe(1);
    expect(result.other).toBe(1);

    const index = await readIndex();
    expect(index).toContain('## Other specs (not in decomposition.md)');
    const otherSection = index.slice(index.indexOf('## Other specs'));
    expect(otherSection).toContain('| orphan |');
  });

  it('treats all specs as active when there is no decomposition.md', async () => {
    await createSpec('alpha');
    await createSpec('bravo');

    const result = await generator.generate();
    expect(result.active).toBe(2);
    expect(result.other).toBe(0);

    const index = await readIndex();
    expect(index).not.toContain('## Other specs');
  });

  it('re-generation is idempotent (byte-identical for unchanged state)', async () => {
    await createSpec('alpha');
    await createSpec('bravo');
    await writeDecomposition('alpha\nbravo\n');

    await generator.generate();
    const first = await readIndex();
    await generator.generate();
    const second = await readIndex();

    expect(second).toBe(first);
  });

  it('handles a project with zero specs', async () => {
    const result = await generator.generate();
    expect(result.total).toBe(0);

    const index = await readIndex();
    expect(index).toContain('# Spec Roadmap');
    expect(index).toContain('_No active specs._');
  });

  it('does not match spec names as substrings of other names', async () => {
    await createSpec('auth');
    await createSpec('auth-v2');
    // decomposition mentions only auth-v2; "auth" should NOT be treated as mentioned
    await writeDecomposition('1. auth-v2\n');

    const result = await generator.generate();
    expect(result.active).toBe(1); // auth-v2
    expect(result.other).toBe(1); // auth
  });

  it('rejects deferring a spec that does not exist', async () => {
    await expect(generator.defer('ghost', 'nope')).rejects.toThrow(/not found/);
  });
});
