import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { promises as fs } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import { IndexGenerator } from '../index-generator.js';

const ALL_PHASES = {
  requirements: '# Requirements\n',
  design: '# Design\n',
  tasks: '- [x] 1. Done task\n- [ ] 2. Pending task\n',
};

describe('IndexGenerator', () => {
  let tempDir: string;
  let generator: IndexGenerator;

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(join(tmpdir(), 'index-gen-test-'));
    await fs.mkdir(join(tempDir, '.spec-workflow', 'specs'), { recursive: true });
    generator = new IndexGenerator(tempDir);
  });

  afterEach(async () => {
    await fs.rm(tempDir, { recursive: true, force: true });
  });

  async function createSpec(name: string, files: Partial<typeof ALL_PHASES> = ALL_PHASES) {
    const dir = join(tempDir, '.spec-workflow', 'specs', name);
    await fs.mkdir(dir, { recursive: true });
    if (files.requirements !== undefined) await fs.writeFile(join(dir, 'requirements.md'), files.requirements);
    if (files.design !== undefined) await fs.writeFile(join(dir, 'design.md'), files.design);
    if (files.tasks !== undefined) await fs.writeFile(join(dir, 'tasks.md'), files.tasks);
  }

  async function writeDecomposition(content: string) {
    const dir = join(tempDir, '.spec-workflow', 'spec-decomposition');
    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(join(dir, 'decomposition.md'), content);
  }

  async function readIndex(): Promise<string> {
    return fs.readFile(join(tempDir, '.spec-workflow', 'spec-decomposition', 'INDEX.md'), 'utf-8');
  }

  it('marks the file as auto-generated', async () => {
    await generator.generate();
    const index = await readIndex();
    expect(index).toContain('AUTO-GENERATED by spec-workflow-mcp');
    expect(index).toContain('# Spec Roadmap');
  });

  it('orders active specs by their first mention in decomposition.md', async () => {
    await createSpec('alpha');
    await createSpec('bravo');
    await createSpec('charlie');
    await writeDecomposition('# Plan\n\n1. charlie\n2. alpha\n3. bravo\n');

    const result = await generator.generate();
    expect(result.active).toBe(3);

    const index = await readIndex();
    const order = ['charlie', 'alpha', 'bravo'].map(n => index.indexOf(`| ${n} |`));
    expect(order[0]).toBeLessThan(order[1]);
    expect(order[1]).toBeLessThan(order[2]);
    expect(index).toContain('| 1 | charlie |');
    expect(index).toContain('| 3 | bravo |');
  });

  it('derives the status label per phase', async () => {
    await createSpec('needs-reqs', {}); // empty spec dir → requirements not yet started
    await createSpec('done', {
      requirements: '# R\n',
      design: '# D\n',
      tasks: '- [x] 1. a\n- [x] 2. b\n',
    });
    await writeDecomposition('needs-reqs\ndone\n');

    await generator.generate();
    const content = await readIndex();
    expect(content).toMatch(/\| needs-reqs \| Requirements \| — \|/);
    expect(content).toMatch(/\| done \| Complete \| 2\/2 \|/);
  });

  it('renders a Deferred section and excludes deferred specs from Active', async () => {
    await createSpec('alpha');
    await createSpec('bravo');
    await writeDecomposition('alpha\nbravo\n');

    await generator.defer('bravo', 'Postponed until post-launch');
    const result = await generator.generate();

    expect(result.active).toBe(1);
    expect(result.deferred).toBe(1);

    const index = await readIndex();
    expect(index).toContain('## Deferred');
    expect(index).toContain('| bravo | Implementing | Postponed until post-launch |');
    // bravo must not appear in the Active table
    const activeSection = index.slice(index.indexOf('## Active'), index.indexOf('## Deferred'));
    expect(activeSection).not.toContain('| bravo |');
  });

  it('undefer returns a spec to the active roadmap', async () => {
    await createSpec('alpha');
    await writeDecomposition('alpha\n');

    await generator.defer('alpha', 'later');
    await generator.undefer('alpha');
    const result = await generator.generate();

    expect(result.deferred).toBe(0);
    expect(result.active).toBe(1);
    const index = await readIndex();
    expect(index).not.toContain('## Deferred');
  });

  describe('listDeferredSpecs', () => {
    it('returns only deferred specs, with their marker details', async () => {
      await createSpec('alpha');
      await createSpec('bravo');
      await generator.defer('bravo', 'Postponed until post-launch');

      const deferred = await generator.listDeferredSpecs();

      expect(deferred).toHaveLength(1);
      expect(deferred[0].name).toBe('bravo');
      expect(deferred[0].reason).toBe('Postponed until post-launch');
      expect(deferred[0].deferredAt).toMatch(/^\d{4}-\d{2}-\d{2}T/);
    });

    it('returns an empty array when nothing is deferred', async () => {
      await createSpec('alpha');
      expect(await generator.listDeferredSpecs()).toEqual([]);
    });

    it('returns an empty array when the specs directory is missing', async () => {
      const bare = await fs.mkdtemp(join(tmpdir(), 'index-gen-bare-'));
      try {
        expect(await new IndexGenerator(bare).listDeferredSpecs()).toEqual([]);
      } finally {
        await fs.rm(bare, { recursive: true, force: true });
      }
    });

    it('sorts by spec name', async () => {
      for (const name of ['charlie', 'alpha', 'bravo']) {
        await createSpec(name);
        await generator.defer(name, `reason for ${name}`);
      }

      const names = (await generator.listDeferredSpecs()).map(s => s.name);
      expect(names).toEqual(['alpha', 'bravo', 'charlie']);
    });

    it('ignores a malformed marker file', async () => {
      await createSpec('alpha');
      await fs.writeFile(
        join(tempDir, '.spec-workflow', 'specs', 'alpha', 'deferred.json'),
        '{ not valid json'
      );

      expect(await generator.listDeferredSpecs()).toEqual([]);
    });

    it('reflects undefer', async () => {
      await createSpec('alpha');
      await generator.defer('alpha', 'later');
      expect(await generator.listDeferredSpecs()).toHaveLength(1);

      await generator.undefer('alpha');
      expect(await generator.listDeferredSpecs()).toEqual([]);
    });
  });

  it('lists specs missing from decomposition.md under Other specs', async () => {
    await createSpec('alpha');
    await createSpec('orphan');
    await writeDecomposition('alpha\n');

    const result = await generator.generate();
    expect(result.active).toBe(1);
    expect(result.other).toBe(1);

    const index = await readIndex();
    expect(index).toContain('## Other specs (not in decomposition.md)');
    const otherSection = index.slice(index.indexOf('## Other specs'));
    expect(otherSection).toContain('| orphan |');
  });

  it('treats all specs as active when there is no decomposition.md', async () => {
    await createSpec('alpha');
    await createSpec('bravo');

    const result = await generator.generate();
    expect(result.active).toBe(2);
    expect(result.other).toBe(0);

    const index = await readIndex();
    expect(index).not.toContain('## Other specs');
  });

  describe('Next section', () => {
    const COMPLETE = { ...ALL_PHASES, tasks: '- [x] 1. Done task\n' };

    it('renders the routing decision and returns it from generate()', async () => {
      await createSpec('alpha');
      await writeDecomposition('alpha\n');

      const result = await generator.generate();
      expect(result.routing).toMatchObject({ state: 'active', spec: 'alpha' });

      const index = await readIndex();
      expect(index).toContain('## Next');
      expect(index).toContain('- **State:** active');
      expect(index).toContain('- **Spec:** alpha');
    });

    // The incident this section exists for: every sequenced spec is Complete, so the
    // old "first not-Complete in ## Active" rule fell through and reported the roadmap
    // finished while live work sat in ## Other specs.
    it('names the started residual spec when every sequenced spec is Complete', async () => {
      await createSpec('shipped', COMPLETE);
      await createSpec('untouched', { ...ALL_PHASES, tasks: '- [ ] 1. Nothing yet\n' });
      await createSpec('half-built', { ...ALL_PHASES, tasks: '- [x] 1. Done\n- [ ] 2. Todo\n' });
      await writeDecomposition('shipped\n');

      const result = await generator.generate();
      expect(result.routing).toMatchObject({ state: 'active', spec: 'half-built' });

      const index = await readIndex();
      expect(index).toContain('- **Spec:** half-built');
    });

    it('reports all-on-disk-complete instead of claiming the roadmap is finished', async () => {
      await createSpec('shipped', COMPLETE);
      await writeDecomposition('shipped\n');

      const result = await generator.generate();
      expect(result.routing.state).toBe('all-on-disk-complete');
      expect(result.routing.reason).toContain('decomposition.md');
    });

    it('stops rather than guessing when nothing distinguishes the residual specs', async () => {
      await createSpec('shipped', COMPLETE);
      await createSpec('one', { ...ALL_PHASES, tasks: '- [ ] 1. Todo\n' });
      await createSpec('two', { ...ALL_PHASES, tasks: '- [ ] 1. Todo\n' });
      await writeDecomposition('shipped\n');

      const result = await generator.generate();
      expect(result.routing.state).toBe('ambiguous');
      expect(result.routing.candidates).toEqual(['one (0/1)', 'two (0/1)']);
    });

    // The heading is '## Next' precisely so that '## Active spec' — a prefix of
    // '## Active' — never exists. Readers locate sections with indexOf; a colliding
    // heading would silently widen the window instead of failing.
    it('does not disturb indexOf-based section slicing', async () => {
      await createSpec('alpha');
      await createSpec('bravo');
      await writeDecomposition('alpha\nbravo\n');
      await generator.defer('bravo', 'later');
      await generator.generate();

      const index = await readIndex();
      const activeSection = index.slice(index.indexOf('## Active'), index.indexOf('## Deferred'));
      expect(activeSection).toContain('| 1 | alpha |');
      expect(activeSection).not.toContain('| bravo |');
      expect(activeSection).not.toContain('## Next');
      expect(index.indexOf('## Next')).toBeLessThan(index.indexOf('## Active'));
    });
  });

  it('re-generation is idempotent (byte-identical for unchanged state)', async () => {
    await createSpec('alpha');
    await createSpec('bravo');
    await writeDecomposition('alpha\nbravo\n');

    await generator.generate();
    const first = await readIndex();
    await generator.generate();
    const second = await readIndex();

    expect(second).toBe(first);
  });

  it('handles a project with zero specs', async () => {
    const result = await generator.generate();
    expect(result.total).toBe(0);

    const index = await readIndex();
    expect(index).toContain('# Spec Roadmap');
    expect(index).toContain('_No active specs._');
  });

  it('does not match spec names as substrings of other names', async () => {
    await createSpec('auth');
    await createSpec('auth-v2');
    // decomposition mentions only auth-v2; "auth" should NOT be treated as mentioned
    await writeDecomposition('1. auth-v2\n');

    const result = await generator.generate();
    expect(result.active).toBe(1); // auth-v2
    expect(result.other).toBe(1); // auth
  });

  it('rejects deferring a spec that does not exist', async () => {
    await expect(generator.defer('ghost', 'nope')).rejects.toThrow(/not found/);
  });
});
