import { promises as fs } from 'fs';
import { join } from 'path';
import { PathUtils } from './path-utils.js';
import { SpecParser } from './parser.js';
import { deriveSpecStatus } from './spec-status-deriver.js';
import { DeferredSpecMarker, SpecIndexEntry } from '../types.js';

const AUTO_GENERATED_HEADER = [
  '<!-- AUTO-GENERATED by spec-workflow-mcp (spec-index tool). Do not edit by hand — changes are overwritten on regeneration. -->',
  '<!-- Active order follows each spec\'s first mention in decomposition.md; status is derived from each spec\'s documents (same logic as spec-status). Regenerate with the spec-index tool (action: generate). -->',
].join('\n');

/** Short labels for the roadmap table, keyed by overallStatus. */
const STATUS_LABELS: Record<string, string> = {
  'requirements-needed': 'Requirements',
  'design-needed': 'Design',
  'tasks-needed': 'Tasks',
  'ready-for-implementation': 'Ready',
  'implementing': 'Implementing',
  'completed': 'Complete',
};

export interface IndexResult {
  path: string;
  total: number;
  active: number;
  deferred: number;
  other: number;
}

/**
 * Generates INDEX.md — the multi-spec roadmap roll-up — from spec state on disk.
 * Modeled on DeferralStorage: full deterministic re-serialize and overwrite, so the
 * same on-disk state always produces a byte-identical file (idempotent re-generation).
 */
export class IndexGenerator {
  constructor(private projectPath: string) {}

  /** (Re)write INDEX.md from current spec state. */
  async generate(): Promise<IndexResult> {
    const parser = new SpecParser(this.projectPath);
    const specs = await parser.getAllSpecs();
    const decompContent = await this.readDecomposition();
    const hasDecomposition = decompContent.trim().length > 0;

    const entries: SpecIndexEntry[] = [];
    for (const spec of specs) {
      const marker = await this.readDeferredMarker(spec.name);
      const { currentPhase, overallStatus } = deriveSpecStatus(spec);
      entries.push({
        name: spec.name,
        currentPhase,
        overallStatus,
        taskProgress: spec.taskProgress ?? { total: 0, completed: 0, pending: 0 },
        createdAt: spec.createdAt,
        deferred: marker !== null,
        deferredReason: marker?.reason,
        inDecomposition: hasDecomposition && this.mentionIndex(decompContent, spec.name) >= 0,
      });
    }

    const { active, deferred, other } = this.categorize(entries, decompContent);
    const content = this.render(active, deferred, other);

    await fs.mkdir(PathUtils.getDecompositionPath(this.projectPath), { recursive: true });
    const indexPath = PathUtils.getIndexPath(this.projectPath);
    await fs.writeFile(indexPath, content, 'utf-8');

    return {
      path: indexPath,
      total: entries.length,
      active: active.length,
      deferred: deferred.length,
      other: other.length,
    };
  }

  /** Mark a spec as deferred (must exist on disk). Caller is responsible for regenerating. */
  async defer(specName: string, reason: string): Promise<void> {
    const specPath = PathUtils.getSpecPath(this.projectPath, specName);
    try {
      const stats = await fs.stat(specPath);
      if (!stats.isDirectory()) throw new Error('not a directory');
    } catch {
      throw new Error(`Spec '${specName}' not found`);
    }
    const marker: DeferredSpecMarker = {
      deferred: true,
      reason,
      deferredAt: new Date().toISOString(),
    };
    await fs.writeFile(this.deferredMarkerPath(specName), JSON.stringify(marker, null, 2) + '\n', 'utf-8');
  }

  /** Clear a spec's deferred marker. No-op if the spec is not deferred. */
  async undefer(specName: string): Promise<void> {
    try {
      await fs.unlink(this.deferredMarkerPath(specName));
    } catch {
      // Not deferred — nothing to do.
    }
  }

  private categorize(entries: SpecIndexEntry[], decompContent: string) {
    const hasDecomposition = decompContent.trim().length > 0;
    const deferred = [...entries.filter(e => e.deferred)].sort((a, b) => a.name.localeCompare(b.name));
    const nonDeferred = entries.filter(e => !e.deferred);

    let active: SpecIndexEntry[];
    let other: SpecIndexEntry[];

    if (hasDecomposition) {
      active = nonDeferred
        .filter(e => e.inDecomposition)
        .sort((a, b) =>
          (this.mentionIndex(decompContent, a.name) - this.mentionIndex(decompContent, b.name)) ||
          a.name.localeCompare(b.name));
      other = nonDeferred
        .filter(e => !e.inDecomposition)
        .sort((a, b) => a.createdAt.localeCompare(b.createdAt) || a.name.localeCompare(b.name));
    } else {
      // No decomposition yet: everything is "active", ordered by creation (rough build order).
      active = [...nonDeferred].sort((a, b) => a.createdAt.localeCompare(b.createdAt) || a.name.localeCompare(b.name));
      other = [];
    }

    return { active, deferred, other };
  }

  private render(active: SpecIndexEntry[], deferred: SpecIndexEntry[], other: SpecIndexEntry[]): string {
    const lines: string[] = [AUTO_GENERATED_HEADER, '', '# Spec Roadmap', ''];

    lines.push('## Active', '');
    if (active.length === 0) {
      lines.push('_No active specs._', '');
    } else {
      lines.push('| # | Spec | Status | Progress |', '| --- | --- | --- | --- |');
      active.forEach((e, i) => {
        lines.push(`| ${i + 1} | ${e.name} | ${this.label(e)} | ${this.progress(e)} |`);
      });
      lines.push('');
    }

    if (deferred.length > 0) {
      lines.push('## Deferred', '');
      lines.push('| Spec | Status | Reason |', '| --- | --- | --- |');
      deferred.forEach(e => {
        lines.push(`| ${e.name} | ${this.label(e)} | ${this.cell(e.deferredReason || '')} |`);
      });
      lines.push('');
    }

    if (other.length > 0) {
      lines.push('## Other specs (not in decomposition.md)', '');
      lines.push('| Spec | Status | Progress |', '| --- | --- | --- |');
      other.forEach(e => {
        lines.push(`| ${e.name} | ${this.label(e)} | ${this.progress(e)} |`);
      });
      lines.push('');
    }

    return lines.join('\n').trimEnd() + '\n';
  }

  private label(e: SpecIndexEntry): string {
    return STATUS_LABELS[e.overallStatus] || e.overallStatus;
  }

  private progress(e: SpecIndexEntry): string {
    const { total, completed } = e.taskProgress;
    return total > 0 ? `${completed}/${total}` : '—';
  }

  /** Escape free text for a single markdown table cell. */
  private cell(text: string): string {
    return text.replace(/\|/g, '\\|').replace(/\s*\n+\s*/g, ' ').trim();
  }

  /** Index of the spec name's first whole-token mention in decomposition.md, or -1. */
  private mentionIndex(content: string, name: string): number {
    if (!content) return -1;
    const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const match = new RegExp(`(?<![\\w-])${escaped}(?![\\w-])`).exec(content);
    return match ? match.index : -1;
  }

  private deferredMarkerPath(specName: string): string {
    return join(PathUtils.getSpecPath(this.projectPath, specName), 'deferred.json');
  }

  private async readDeferredMarker(specName: string): Promise<DeferredSpecMarker | null> {
    try {
      const raw = await fs.readFile(this.deferredMarkerPath(specName), 'utf-8');
      const parsed = JSON.parse(raw);
      if (parsed && parsed.deferred === true && typeof parsed.reason === 'string') {
        return parsed as DeferredSpecMarker;
      }
      return null;
    } catch {
      return null;
    }
  }

  private async readDecomposition(): Promise<string> {
    try {
      return await fs.readFile(
        join(PathUtils.getDecompositionPath(this.projectPath), 'decomposition.md'),
        'utf-8'
      );
    } catch {
      return '';
    }
  }
}
